import test from 'ava'
import {alphabeticalKeys, deepEqual} from '../../modules/lib/utilities.js'

test(`does deep equal util work`, t => {
    t.truthy(deepEqual({x: 1}, {x: 1}))
    t.truthy(deepEqual(
        {x: {y: {arr: [1,2,3]}}},
        {x: {y: {arr: [1,2,3]}}}
    ))
})

test('assign letter as key to object', t => {
    const arrOfObjs = [
        {name: 'generic object thingy A'},
        {name: 'generic object thingy B'},
        {name: 'generic object thingy c'},
        {name: 'generic object thingy d'},
        {name: 'generic object thingy e'},
        {name: 'generic object thingy f'},
        {name: 'generic object thingy g'},
        {name: 'generic object thingy h'},
        {name: 'generic object thingy i'},
        {name: 'generic object thingy j'},
        {name: 'generic object thingy k'},
        {name: 'generic object thingy l'},
        {name: 'generic object thingy m'},
        {name: 'generic object thingy n'},
        {name: 'generic object thingy o'},
        {name: 'generic object thingy p'},
        {name: 'generic object thingy q'},
        {name: 'generic object thingy r'},
        {name: 'generic object thingy s'},
        {name: 'generic object thingy t'},
        {name: 'generic object thingy u'},
        {name: 'generic object thingy v'},
        {name: 'generic object thingy w'},
        {name: 'generic object thingy x'},
        {name: 'generic object thingy y'},
        {name: 'generic object thingy z'},
        {name: 'generic object thingy aa'},
        {name: 'generic object thingy bb'},
        {name: 'generic object thingy cc'},
        {name: 'generic object thingy dd'},
        {name: 'generic object thingy ee'},
        {name: 'generic object thingy ff'},
        {name: 'generic object thingy gg'},
        {name: 'generic object thingy hh'},
        {name: 'generic object thingy ii'},
        {name: 'generic object thingy jj'},
        {name: 'generic object thingy kk'},
        {name: 'generic object thingy ll'},
        {name: 'generic object thingy mm'},
        {name: 'generic object thingy nn'},
        {name: 'generic object thingy oo'},
        {name: 'generic object thingy pp'},
        {name: 'generic object thingy qq'},
        {name: 'generic object thingy rr'},
        {name: 'generic object thingy ss'},
        {name: 'generic object thingy tt'},
        {name: 'generic object thingy uu'},
        {name: 'generic object thingy vv'},
        {name: 'generic object thingy ww'},
        {name: 'generic object thingy xx'},
        {name: 'generic object thingy yy'},
        {name: 'generic object thingy zz'},
        {name: 'generic object thingy aaa'},
        {name: 'generic object thingy bbb'},
        {name: 'generic object thingy ccc'},
        {name: 'generic object thingy ddd'},
        {name: 'generic object thingy eee'},
        {name: 'generic object thingy fff'},
        {name: 'generic object thingy ggg'},
    ]
    t.deepEqual(
        alphabeticalKeys(arrOfObjs),
        {
            'a': {name: 'generic object thingy A'},
            'b': {name: 'generic object thingy B'},
            'c': {name: 'generic object thingy c'},
            'd': {name: 'generic object thingy d'},
            'e': {name: 'generic object thingy e'},
            'f': {name: 'generic object thingy f'},
            'g': {name: 'generic object thingy g'},
            'h': {name: 'generic object thingy h'},
            'i': {name: 'generic object thingy i'},
            'j': {name: 'generic object thingy j'},
            'k': {name: 'generic object thingy k'},
            'l': {name: 'generic object thingy l'},
            'm': {name: 'generic object thingy m'},
            'n': {name: 'generic object thingy n'},
            'o': {name: 'generic object thingy o'},
            'p': {name: 'generic object thingy p'},
            'q': {name: 'generic object thingy q'},
            'r': {name: 'generic object thingy r'},
            's': {name: 'generic object thingy s'},
            't': {name: 'generic object thingy t'},
            'u': {name: 'generic object thingy u'},
            'v': {name: 'generic object thingy v'},
            'w': {name: 'generic object thingy w'},
            'x': {name: 'generic object thingy x'},
            'y': {name: 'generic object thingy y'},
            'z': {name: 'generic object thingy z'},
            'aa': {name: 'generic object thingy aa'},
            'bb': {name: 'generic object thingy bb'},
            'cc': {name: 'generic object thingy cc'},
            'dd': {name: 'generic object thingy dd'},
            'ee': {name: 'generic object thingy ee'},
            'ff': {name: 'generic object thingy ff'},
            'gg': {name: 'generic object thingy gg'},
            'hh': {name: 'generic object thingy hh'},
            'ii': {name: 'generic object thingy ii'},
            'jj': {name: 'generic object thingy jj'},
            'kk': {name: 'generic object thingy kk'},
            'll': {name: 'generic object thingy ll'},
            'mm': {name: 'generic object thingy mm'},
            'nn': {name: 'generic object thingy nn'},
            'oo': {name: 'generic object thingy oo'},
            'pp': {name: 'generic object thingy pp'},
            'qq': {name: 'generic object thingy qq'},
            'rr': {name: 'generic object thingy rr'},
            'ss': {name: 'generic object thingy ss'},
            'tt': {name: 'generic object thingy tt'},
            'uu': {name: 'generic object thingy uu'},
            'vv': {name: 'generic object thingy vv'},
            'ww': {name: 'generic object thingy ww'},
            'xx': {name: 'generic object thingy xx'},
            'yy': {name: 'generic object thingy yy'},
            'zz': {name: 'generic object thingy zz'},
            'aaa': {name: 'generic object thingy aaa'},
            'bbb': {name: 'generic object thingy bbb'},
            'ccc': {name: 'generic object thingy ccc'},
            'ddd': {name: 'generic object thingy ddd'},
            'eee': {name: 'generic object thingy eee'},
            'fff': {name: 'generic object thingy fff'},
            'ggg': {name: 'generic object thingy ggg'},
        }
    )
})
